export const ADD_GOOD_IN_BASKET =  'ADD_GOOD_IN_BASKET';
export const UPDATE_CATEGORIES = 'UPDETE_CATEGORIES';
export const UPDATE_GOODS = 'UPDATE_GOODS';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
export const CHANGE_ACTIVECATEGORY = 'CHANGE_ACTIVECATEGORY';
export const CHANGE_ACTIVEGOOD = 'CHANGE_ACTIVEGOOD';
export const ADD_GOODS_FOR_HOME = 'ADD_GOODS_FOR_HOME ';
export const  UPDATE_COLORS = 'ADD_GOODS_COLORS ';
export const  ADD_BRANDS = 'ADD_GOODS_BRANDS ';
export const  ADD_FILTER = 'ADD_FILTER';
export const  CLEAR_FILTER = 'CLEAR_FILTER';
export const  ADD_GOODS_BY_BRAND = 'ADD_GOODS_BY_BRAND ';
export const  CHANGE_PRICE_FILTER = 'CHANGE_PRICE_FILTER';
export const  GET_PRICE_RANGE = 'GET_PRICE_RANGE';
export const  CUSTOM_PRICE_RANGE = 'CUSTOM_PRICE_RANGE';



